steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '--build-arg=NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyBmikSXMj__EKaU-O0UsbnZ5J6pop31mT0'
      - '--build-arg=NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=wayfound-prod-841dd.firebaseapp.com'
      - '--build-arg=NEXT_PUBLIC_FIREBASE_PROJECT_ID=wayfound-prod-841dd'
      - '--build-arg=NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=wayfound-prod-841dd.firebasestorage.app'
      - '--build-arg=NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=969171216962'
      - '--build-arg=NEXT_PUBLIC_FIREBASE_APP_ID=1:969171216962:web:2d848ff27790b31dc9dbdb'
      - '--build-arg=NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=G-GJ9S1VCD8P'
      - '--build-arg=NEXT_PUBLIC_BASE_URL=https://gowayfound.com'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/wayfound/app'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/wayfound/app']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'wayfound'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/wayfound/app'
      - '--region=us-central1'
      - '--project=$PROJECT_ID'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=1Gi'
      - '--min-instances=1'
      - '--max-instances=10'

options:
  logging: CLOUD_LOGGING_ONLY
